
DROP TABLE IF EXISTS Score_Hole;
DROP TABLE IF EXISTS Score;
-- DROP TABLE IF EXISTS Buddylist;
DROP TABLE IF EXISTS Course_moderators;
DROP TABLE IF EXISTS Round;
DROP TABLE IF EXISTS Hole;
DROP TABLE IF EXISTS Player;
DROP TABLE IF EXISTS Course;
